services:
  - type: web
    name: student-profile-analyzer
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python create_db.py"
    startCommand: "gunicorn app:app"
