services:
  - type: web
    name: student-profile-analyzer
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r backend/requirements.txt && python backend/create_db.py"
    startCommand: "gunicorn --chdir backend app:app"
